### ISSUE TITLE
Should there be a Ui.Class module?

### ISSUE THREAD

**Issue by arsduo** [danielnarey/elm-modular-ui#3]
Hi! We've been using Modular.Ui and it's been really great! Thank you for putting the library together.

One thing that confused me starting out and has confused a few other people is that all CSS classes are manipulated through Ui.Modifier. As far as I can tell from the Bulma docs, all modifiers are CSS classes, but not all CSS classes are modifiers. Using `Ui.Modifier.add` to add CSS classes feels a bit strange (and has probably resulted in a number of `is-something` and `has-something` classes that aren't actually modifiers).

What do you think about having a `Ui.Class` module in addition to `Ui.Modifier`? Functionally they'd be identical, which is a big drawback, but conceptually it might make it easier for people (especially those of us less familiar with Bulma) to start using the library. 

If this sounds like something you're interested in, I'd be happy to submit a pull request!

**Comment by danielnarey** [comment]
Hi Alex,

You're correct in terms of the semantics of the package that `Ui.Modifier.add` and `Ui.Modifier.addList` are intended to be used when applying modifier classes, which always start with "is-" or "has-" according to Bulma's semantics.  So I can understand why applying `Ui.Modifier.add "box"` or `Ui.Modifier.add "content"` to a block of text, for example, would feel like a mistake. Here's some background on this: 

Initially, I intended to include constructors for all of the Bulma element classes in the Modular UI package and then to release a companion package that would have constructors for Bulma components and layout classes. Given the full set of constructors, `Ui.Modifier.add` would only need to be used with actual modifier classes. However, in creating the initial package, it seemed redundant to have a constructor that didn't do anything but apply a single class to an element, so I left out constructors for Bulma's "box", "content", and "table" element classes. I have not yet released the companion package because it is incomplete, so for now component and layout classes have to be added explicitly as well, which I assume you've probably been doing. 

I'm not convinced that a `Ui.Class` module is a good solution because, as you point out, `Ui.Class.add` and `Ui.Modifier.add` would be interchangeable, and I think that could lead to more confusion. My initial plan to have a constructor for every non-modifier class in Bulma is also an imperfect solution because it doesn't allow for extending Bulma with custom element and component classes. The solution I would prefer would be for Modular UI to have a "custom" element/component constructor that would include a single class name as one of its arguments (or to have several such constructors). This would also help to enforce the idea that a DOM node can have many modifier classes, but should have no more than one element or component class. 

Currently, the way to create a generic DOM node in Modular UI is to use `Ui.leaf` for a node with no children, `Ui.textWrapper` for a node with only text, or `Ui.container` for a node with other child nodes. My thought is that this pattern could be extended in a `Ui.Custom` module so that `Ui.Custom.leaf`, `Ui.Custom.textWrapper`, and `Ui.Custom.container` would each take a class argument in addition to a tag argument. For example:

```
"This text is in a box."
  |> Ui.Custom.textWrapper ("p", "box")
```

Do you see any drawbacks to this solution? 

Also, I'm open to names for the new module other than "Custom" if you think something else would be more intuitive. 

Thanks for bringing this issue to my attention,
Daniel

**Comment by carolineartz** [comment]
Hey @danielnarey!  @arsduo and I work together :). Agree that this is difficult and current implementation being suboptimal. I've been thinking about it and your proposed solution above. Here are my thoughts:

I can now see the obstacles around implementing something that solves this but also makes sense and is true to Bulma patterns; initially, I thought the decision to add a `Ui.Class` or `Ui.addClass/Ui.addClassList` was trivial. 

I do think your solution above is, at the very least, adequate to solve this, but I'm not a huge fan of `Custom`. I've seen this pattern of using the term "custom", but I tend to find these usages counterintuitive. To me, `Custom` here would imply a module with the job of adding attributes beyond the standard for the node types, and/or be constructing non-standard HTML nodes, like `<column />`...or something else.

For this, I might have chosen `Ui.Element`, but as this is a record that wraps `Dom.Element`, it would be difficult to implement without breaking the interface. 

You could do something like `HTMLElement`, but it since it wouldn't actually limit the node construction to DOM elements of HTML subtype since you could easily pass in `svg`, or whatever string you wanted. you could use `Ui.Object`. Not sure...

Regardless of the choice, including `Custom`, I'd love to see this sooner than later!

**Comment by carolineartz** [comment]
Another thing I thought of but doesn't easily account for lists would be to shift the interface to `Ui.Modifier` to functions within a `Ui.Class` module -- keeping the existing interface for backwards compatibility.

```elm
Ui.Class.modifier.is "notification"
Ui.Class.modifier.has "text-centered"
```

**Comment by danielnarey** [comment]
Thanks for the insight, @carolineartz. I agree with you about why not to make this a "custom" module.

After thinking about it, it seems like any truly satisfactory solution would be a major version change, so I'm reconsidering the initial suggestion — I didn't like the idea of a `Ui.Class` module, but having a generic `addClass` function in the base `Ui` module makes more sense to me, because you would only need to call it when you use one of the generic constructors. 

Here is what the resulting pattern would look like:

```
"This text is in a box."
  |> Ui.textWrapper "p"
  |> Ui.addClass "box"
  |> Ui.Modifier.addList
    [ "is-size-3"
    , "has-text-weight-bold"
    , "has-text-centered"
    ]
```

Make sense? 

Watch for the new version release in the next couple days.

**Comment by arsduo** [comment]
I like this solution a lot! I'd also suggest adding `Ui.addClassList` to make it easy to add multiple classes and for consistency with the rest of the library.

I'm sure you've thought about this already, but it's useful for my own thinking to write out: one of the advantages this approach will have is that it makes `Ui` more intuitive for users who aren't using Bulma. I suspect there are plenty of Elm projects out there that might be open to a significantly smoother way of building HTML, as long as it can fit smoothly in with whatever CSS framework they've already invested in. 

`Ui` already works well with non-Bulma frameworks (I'm using it with a personal project on Bootstrap), fwiw -- steps like it will make it even easier to build more community, which in turn will produce more of the packages (like a drag-and-drop library, another current project) that make it easier to switch to.

**Comment by danielnarey** [comment]
@arsduo, In terms of the bigger picture, I could see the value in creating a stripped-down version of this package that doesn't reference Bulma and would be more intuitive to use alongside other CSS frameworks. For the moment, however, could you give me a use case with Bootstrap or another framework where you are adding multiple classes and it would seem wrong to use `Ui.Modifier.addList`?

**Comment by carolineartz** [comment]
We use this for a large production app where we need to add classes for JavaScript interop, outside the scope of Bulma.

**Comment by arsduo** [comment]
To be clear, I don't think you'd need to strip it down at all! I think the
current package works quite well for both Bulma and non-Bulma apps;
Modifier has been the only part that didn't feel applicable across
frameworks. I was more thinking of whether it's positioned as "for Bulma"
or "for any Elm app, with a number of convenient helpers if you're using
Bulma."

As an example of multiple classes, Bootstrap uses a number of classes for
table behavior/buttons/etc. (".table .table-striped", ".btn .btn-primary").
Conceptually users would think of those as classes, not modifiers, since
the modifier concept doesn't exist in that framework. (As with the original
question, it's just a matter of naming and concepts, not function.)

**Comment by danielnarey** [comment]
This is the last I will say about it for now, but I do think the pattern I am recommending will work for Bootstrap:

```
"Click Me"
  |> Ui.textWrapper "button"
  |> Ui.Action.add ("click", Msg.DoSomething)
  |> Ui.addClass "btn"
  |> Ui.Modifier.addList
    [ "btn-primary"
    , "btn-lg"
    ]
```

or Foundation: 

```
"Click Me"
  |> Ui.Button.action Msg.DoSomething
  |> Ui.Modifier.addList
    [ "primary"
    , "large"
    ]
```

The "is-" and "has-" prefixes are specific to Bulma, but I think the concept of a modifier transfers to other frameworks in a straightforward way. 

For legacy CSS or custom sets of classes outside of a framework (as mentioned by @carolineartz), I don't know; there may be cases where the pattern wouldn't apply at all, but an example isn't coming to mind for me. 

My current opinion is that adding a `Ui.addClassList` function would break the existing pattern by making the `Ui.Modifier` module redundant, and I'm not yet convinced of the need for this function. If you find that the modifier concept is still a source of confusion, another route might be to improve the package documentation (*pull requests encouraged!*). 

Thanks again for the input and insight from your team.

**Comment by carolineartz** [comment]
This is the last I'll say too! I respect your position on maintaining the pattern, and completely agree that the concept of modifiers extends beyond Bulma-- conceptually its just an alternative stylings; `btn-primary`/`btn-secondary` are perfect examples from Bootstrap. 

That said, I don't think the addition of a `Ui.addClassList` would (or should?) cause confusion, nor would it negate the use case for `Ui.Modifier`. Just looking at the source of the Bulma documentation, it's clear that the need for additional classes beyond modifiers is at least accepted if not expected, while still relying heavily on the base pattern. In our codebase, I promote the use of data attributes whenever the javascript interop is not related to presentation. When it is related to presentation, or required due to some 3rd party api, classes are the appropriate choice conceptually, IMO. 

Ultimately I'm meaning to say that aliases are commonly applied in elm when the semantics achieve readable, maintainable code. This is a case where I think both concepts apply.

Thanks again for this library, it's been a pleasure to work with and I've been doing my best to promote it at Elm meetups in Chicago!

**Comment by danielnarey** [comment]
@carolineartz, I hear you, and I think both points of view are valid. I'm inclined to say that the issue will be resolved with the next major version. I'd like the solution to be an improved pattern that takes different production contexts into account, rather than splitting into multiple patterns.
